//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace creditcharges.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("creditcharges.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addImg {
            get {
                object obj = ResourceManager.GetObject("addImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerated Harvesting,Agribusiness,Airman Development,Alimentos,Aurora,Borden,Corner Place,Cross,Daylight Donuts,Dimmitt Bistro,Golden Chick-Dalhart,Golden Chick-Dumas,Harvesting,Hilmar,IMTS,Integrity Autos,Lab,Lava You,Little Caesars,Little Caesars-Dumas,Little Caesars-Pampa,Little Caesars-Perryton,Micro,Mi Taquito ,Outlier,Pilot,Promised Land,San Antonio,Shop,SMP,Testing,To Distribute,Wolf Express,Little Caesars-Dalhart,Wash,IABS,Airman Property Development LLC,Golden Chick-Borger,Little Caesars-Borger,I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CLASS {
            get {
                return ResourceManager.GetString("CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerated Harvesting,Airman Development,Alimentos,IMTS,Integrity Autos,Outlier,Pilot,Promised Land,Select Logixtics,Mi Taquito ,Cross,Airman Property Development LLC,Integrated Dairy Consulting .
        /// </summary>
        internal static string ENTITIES {
            get {
                return ResourceManager.GetString("ENTITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18-01	Nelson Faria Roof,18-02	Jason Faria Roof,18-03	1713 Tumbleweed,18-05	Cross Apt 1,18-06	Cross Apt 2,18-07	Cross New Shop,18-08	Cross Office Expansion,18-09	Nelson Faria Patio,18-10	708 Melinda,18-11	712 Melinda,18-12	716 Melinda,18-13	720 Melinda,18-14	724 Melinda,18-15	Jason Room Addition,18-17	Golden Chick Dalhart,18-18	Little Caesars Dalhart,18-19	Nelson Landscape Project,18-20	Cross Apt 3,18-21	Nelson Well Repair,18-23	Jason Faria Entry Door,18-24	1700 Cactus Flower Dalhart,18-25	1701 Cactus Flower [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JOBS {
            get {
                return ResourceManager.GetString("JOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron Gonzalez
        ///Aaron Richard
        ///Abdel Domingo
        ///Abdiel Silva
        ///Abel Espinoza
        ///Adam Escobar
        ///Adolfo Molina
        ///Adonis Suarez
        ///Adonis Torriente
        ///Adrian Romero
        ///Adrian Suarez
        ///Alberto Valdez
        ///Alejandro Martinez
        ///Alex Orozco
        ///Alexander Gutierrez
        ///Alexis Briggs
        ///Alfredo Davila
        ///Aliesky Dieguez
        ///Allen Sheets
        ///Amagrui Montenegro
        ///Angel Alvarez
        ///Angel Garcia
        ///Angel Olivas
        ///Anna Quevedo
        ///Anthony Bailey
        ///Armando Hernandez
        ///Armando Medrano
        ///Armando Venereo
        ///Barbaro Parodis
        ///Barron Wesley
        ///Brad Moody
        ///Brandon Sepeda
        ///Brian M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap No_Picture1 {
            get {
                object obj = ResourceManager.GetObject("No_Picture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerated Harvesting,Accounting and Bookeeping,Accounts Payable,Advertising and Promotion,Alimentos FBM-2817,Alimentos FBSW-0511,Ask Emilio,Ask My Accountant,Attorney Fees,Auto and Truck Expenses-Repairs and Maintenance,Automobile Expense,Background Check,Bank Service Charges,Bistro Food,Blueprints,Business Licenses and Permits,Car and Truck Expenses,Cell Phone Expense,Certifications,CGS-Dump Fees,CGS-Equipment Rental for Jobs,CGS-Other Construction Costs,Child Support,CMC-Appliances/Stoves/Micro/Dishwas, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QBAT {
            get {
                return ResourceManager.GetString("QBAT", resourceCulture);
            }
        }
    }
}
